services:
  #  app:
  #    image: 'janpeterd/jp-file-share-service:latest'
  #    ports:
  #      - '8080:8080'
  #    environment:
  #      - 'JWT_SECRET=QgbVeGzBDttzG6UlMHF/WH9+rSqaeR+X7sMh38O5dJU8sspCUPxkguqN2T+lsMX7'
  #      - 'MARIADB_HOST=mariadb'
  #      - 'MARIADB_USER=jp'
  #      - 'MARIADB_PASSWORD=abc123'
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=jp-file-transfer'
      - 'MARIADB_PASSWORD=abc123'
      - 'MARIADB_ROOT_PASSWORD=abc123'
      - 'MARIADB_USER=jp'
    ports:
      - '3306:3306'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

