spring.application.name=transfer
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:192.168.1.138}:${POSTGRES_PORT:5432}/transfer?createDatabaseIfNotExists=true
spring.datasource.username=${POSTGRES_USER:transfer}
spring.datasource.password=${POSTGRES_PASSWORD:transfer}
server.tomcat.max-http-form-post-size=100GB
server.tomcat.max-swallow-size=100GB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100GB
spring.servlet.multipart.max-request-size=100GB
spring.app.jwtSecret=${JWT_SECRET}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.profiles.active=dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.web.client.RestTemplate =DEBUG
apiurl=${API_URL:http://localhost:8080}
frontend.default_url=${FRONTEND_URL:http://localhost:5173}
frontend.urls=${frontend.default_url},http://localhost:3000
cors_urls=${frontend.urls}
admin.username=${ADMIN_USERNAME:admin}
admin.email=${ADMIN_EMAIL:admin@example.com}
admin.password=${ADMIN_PASSWORD:admin}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sso.janpeterdhalle.com/application/o/jp-transfer/
spring.security.oauth2.client.provider.authentik-m2m.issuer-uri=https://sso.janpeterdhalle.com/application/o/jp-transfer/
spring.security.oauth2.client.registration.authentik-m2m.client-id=O9kD9aVFLXufUASHVVKW27oVWHwYXPOrj4tKpyRt
# spring.security.oauth2.client.registration.authentik-m2m.client-secret=ZfHoZNRaoP3AyXvUgXxevF2mJm2QbUCYgSvGEqHNbQghhipS2MmMuZZ6EcktecDea6mFhCUXEvyShvlE9mjQS2Sh6hYaT1FiWJogqk6UxohSMtFUJ1WmnwVuuisOkoOQ
spring.security.oauth2.client.registration.authentik-m2m.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.authentik-m2m.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.authentik.issuer-uri = https://sso.janpeterdhalle.com/application/o/jp-transfer/
authentik.base-url=https://sso.janpeterdhalle.com/api/v3
authentik.client-service-token=EcStCx9j0VV6OCPSO6rieMiu9psn8esDPOWdOfSs7QcpLaSAI8VFWSzZ8zgM
