CREATE TABLE chunk
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_id        BIGINT,
    chunk_index    INTEGER                                 NOT NULL,
    chunk_checksum VARCHAR(40),
    CONSTRAINT pk_chunk PRIMARY KEY (id)
);

CREATE TABLE file_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name     VARCHAR(255),
    file_type     VARCHAR(255),
    file_size     BIGINT                                  NOT NULL,
    total_chunks  INTEGER                                 NOT NULL,
    file_checksum VARCHAR(40),
    transfer_id   BIGINT                                  NOT NULL,
    user_id       BIGINT,
    chunk_size    INTEGER                                 NOT NULL,
    uploaded      BOOLEAN,
    CONSTRAINT pk_fileentity PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id            UUID                        NOT NULL,
    user_id       BIGINT,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expires_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE shared_links
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          VARCHAR(255)                            NOT NULL,
    url           VARCHAR(255)                            NOT NULL,
    download_link VARCHAR(255)                            NOT NULL,
    user_id       BIGINT,
    created_at    BIGINT                                  NOT NULL,
    updated_at    BIGINT                                  NOT NULL,
    expires_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    downloads     INTEGER                                 NOT NULL,
    max_downloads INTEGER                                 NOT NULL,
    CONSTRAINT pk_shared_links PRIMARY KEY (id)
);

CREATE TABLE transfer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active         BOOLEAN                                 NOT NULL,
    start_time     TIMESTAMP WITHOUT TIME ZONE,
    end_time       TIMESTAMP WITHOUT TIME ZONE,
    upload_path    VARCHAR(255),
    user_id        BIGINT,
    shared_link_id BIGINT,
    CONSTRAINT pk_transfer PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    email    VARCHAR(255),
    active   BOOLEAN                                 NOT NULL,
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE transfer
    ADD CONSTRAINT uc_transfer_sharedlink UNIQUE (shared_link_id);

ALTER TABLE chunk
    ADD CONSTRAINT FK_CHUNK_ON_FILE FOREIGN KEY (file_id) REFERENCES file_entity (id);

ALTER TABLE file_entity
    ADD CONSTRAINT FK_FILEENTITY_ON_TRANSFER FOREIGN KEY (transfer_id) REFERENCES transfer (id);

ALTER TABLE file_entity
    ADD CONSTRAINT FK_FILEENTITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE shared_links
    ADD CONSTRAINT FK_SHARED_LINKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE transfer
    ADD CONSTRAINT FK_TRANSFER_ON_SHAREDLINK FOREIGN KEY (shared_link_id) REFERENCES shared_links (id);

ALTER TABLE transfer
    ADD CONSTRAINT FK_TRANSFER_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
